version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sass
    versions:
    - 1.32.11
    - 1.32.5
    - 1.32.6
    - 1.32.7
    - 1.32.8
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.6.2
    - 12.6.3
    - 12.7.0
    - 12.7.1
    - 12.7.2
    - 12.7.3
    - 12.8.0
    - 12.8.1
    - 12.8.3
    - 13.0.1
    - 13.0.10
    - 13.0.13
    - 13.0.16
    - 13.0.2
    - 13.0.6
    - 13.0.7
    - 13.1.1
    - 13.1.2
    - 13.1.3
    - 13.1.5
  - dependency-name: "@sentry/webpack-plugin"
    versions:
    - 1.14.0
    - 1.14.1
    - 1.14.2
    - 1.15.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
    - 5.11.9
  - dependency-name: "@ckeditor/ckeditor5-build-classic"
    versions:
    - 25.0.0
    - 26.0.0
    - 27.0.0
  - dependency-name: "@welldone-software/why-did-you-render"
    versions:
    - 6.0.5
    - 6.1.0
  - dependency-name: react-final-form
    versions:
    - 6.5.2
  - dependency-name: lint-staged
    versions:
    - 10.5.3
