FROM node:12.14.0-alpine
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json /app/package.json
COPY yarn.lock /app/yarn.lock
RUN set http_proxy= && set https_proxy= && yarn config delete proxy && npm config rm https-proxy && npm config rm proxy
RUN yarn
COPY . /app
CMD env SERVER_API_URL=http://backend:5000 CLIENT_API_URL=http://localhost:5000 yarn dev