FROM node:12.14.0-alpine
WORKDIR /app

RUN set http_proxy= && set https_proxy= && yarn config delete proxy && npm config rm https-proxy && npm config rm proxy
ENV PATH /app/node_modules/.bin:$PATH

RUN yarn add lerna -g

COPY package.json /app/package.json
COPY lerna.json /app/lerna.json
COPY bin /app/bin
COPY packages/admin /app/packages/admin
COPY packages/admin-ui /app/packages/admin-ui
COPY packages/api /app/packages/api
COPY packages/app /app/packages/app
COPY packages/client /app/packages/client
COPY packages/client-ui /app/packages/client-ui
COPY packages/di /app/packages/di
COPY packages/manager /app/packages/manager
COPY packages/service /app/packages/service
COPY packages/shared /app/packages/shared
COPY packages/storage /app/packages/storage
RUN yarn install --frozen-lockfile

COPY tsconfig.json /app/tsconfig.json
COPY @types /app/@types

CMD yarn start:dev