#!/bin/bash
docker build \
--build-arg SENTRY_DSN="$SENTRY_DSN" \
--build-arg SENTRY_AUTH_TOKEN="$SENTRY_AUTH_TOKEN" \
--build-arg SENTRY_ORG="$SENTRY_ORG" \
--build-arg SENTRY_PROJECT="$SENTRY_PROJECT" \
--build-arg YM_ACCOUNT_ID="$YM_ACCOUNT_ID" \
--build-arg FB_PIXEL_ID="$FB_PIXEL_ID" \
--build-arg FB_CLIENT_ACCESS_TOKEN="$FB_CLIENT_ACCESS_TOKEN" \
--build-arg SHOP_NAME="$SHOP_NAME" \
--build-arg RELEASE_VERSION="$DOCKER_TAG" \
--build-arg PUBLIC_URL="$PUBLIC_URL" \
--build-arg SERVER_API_URL="$SERVER_API_URL" \
--build-arg INSTAGRAM_URL="$INSTAGRAM_URL" \
--build-arg TIKTOK_URL="$TIKTOK_URL" \
-f $DOCKERFILE_PATH \
-t $IMAGE_NAME .
